version: '3.7'
services:
    mysql:
        image: 'mysql:8.0'
        container_name: mysqlForVintedBot
        working_dir: /application
        volumes:
            - '.:/application'
        command: --default-authentication-plugin=mysql_native_password

        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - "8082:8080"
        depends_on:
            - mysql
#    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
#    GRANT ALL PRIVILEGES ON database_name.* TO 'username'@'localhost';
